### PR TITLE
chore: oneAPI / Modern Clang Compatibility, main branch (2026.08.20.)

### PR DESCRIPTION
**Pull request by krasznaa**
This is to make the build work with oneAPI-2026.1.0.

The oneAPI releases are usually on the latest LLVM versions. So this should be useful for not just the closed source Intel compiler as well.

With oneAPI-2026.1.0, I see the following error with the current code:

```
[build] In file included from /home/krasznaa/ATLAS/projects/acts/acts/Core/src/EventData/PrintParameters.cpp:12:
[build] In file included from /home/krasznaa/ATLAS/projects/acts/acts/Core/include/Acts/Surfaces/Surface.hpp:19:
[build] /home/krasznaa/ATLAS/projects/acts/acts/Core/include/Acts/Material/MaterialSlab.hpp:25:9: error: '#pragma float_control(except, on)' is illegal when precise is disabled
[build]    25 | #pragma float_control(except, on)
[build]       |         ^
```

Apparently one can only explicitly ask for FPEs with precise FP calculations. Which oneAPI doesn't do by default. (But I assume LLVM/clang does.)

Having pondered for a little bit, I thought this could be an acceptable solution here. But I'm not fully-fully clear on this...

### CODE REVIEW

**Comment by krasznaa** [comment]
Pinging @tstreble-ATLAS, as he wrote these pragmas originally as I understand.

**Comment by krasznaa** [comment]
@andiwand, could you have a look? It's not urgent by any means, but I think it will make the code more "formally correct" as well.

**Review by andiwand — APPROVED** [review]
